### ISSUE TITLE
Would you like to provide the file “data”

### ISSUE THREAD

**Issue by BinaryHuang** [duanyiqun/DS-DDPM#2]
I'd be appreciate if you can provide the file "data".When I was running, the system reported an error and failed to find "data/bci_iv//single_sep/single_subject_data_1.mat "and some other files in the ”data“ folder.So I really need the "data" folder you provided. Thank you very much.

**Comment by duanyiqun** [comment]
The training data scale is too large for direct sharing via repo. Meanwhile, most EEG datasets such as SEED, need an application for usage.  So, we will not provide direct downloading links. You need to download the data through the BCI-competition website [https://www.bbci.de/competition/iv/](https://www.bbci.de/competition/iv/). 

Currently, we managed to refactor this repo later after reviewing the process for reliability. The pre-processing scripts and the inference entry will be provided at that time. If you are quite in a hurry, you can write a simple script to process the raw data according to the dataset defined in line 619 [comon_two_stream_sep_gaussion_organal_arc_margin.py](comon_two_stream_sep_gaussion_organal_arc_margin.py) .
