### ISSUE TITLE
Hi,what is 'diffusion_uncon_bci_compiv'

### ISSUE THREAD

**Issue by xiyuanssxx** [duanyiqun/DS-DDPM#4]
ModuleNotFoundError: No module named 'diffusion_uncon_bci_compiv'

**Comment by duanyiqun** [comment]
sorry for the late reply. do you have the log?
The current code is quite messy and needs refactoring. I will update it hopefully soon.

**Comment by xiyuanssxx** [comment]
Maybe not..
Many thanks and looking forward to it! ! !

**Comment by duanyiqun** [comment]
> Maybe not.. Many thanks and looking forward to it! ! !

hi xi yuan, I just have a draft refactor. 
but will have a larger update later this month.

**Comment by xiyuanssxx** [comment]
okay!! i can wait for good news from you

**Comment by xiyuanssxx** [comment]
Hi I just remembered to ask about the multi-class test model mentioned in the paper， will you provide it ？0v0
