### ISSUE TITLE
data preprocessing

### ISSUE THREAD

**Issue by BinaryHuang** [duanyiqun/DS-DDPM#5]
您好，请问什么时候推出用bci_IV_2a的原生数据即可使用的版本；由于对脑电数据不熟练，希望简单地指导一下大概需要如何处理18个.gdf数据（或者标签.mat数据），十分感谢，期待您的回复

**Comment by duanyiqun** [comment]
Hi there, 

Sorry for the late response. 
At this stage, we will only provide processing for mat file. 

I upload a sample data of subject 9 https://huggingface.co/datasets/claudecc/DS-DDPM/blob/main/single_subject_data_9.mat
Basically you need to preprocess the GDF files into this format for each subject of nine.

**Comment by ruizhiyang0204** [comment]
> 您好，请问什么时候推出用bci_IV_2a的原生数据即可使用的版本；由于对脑电数据不熟练，希望简单地指导一下大概需要如何处理18个.gdf数据（或者标签.mat数据），十分感谢，期待您的回复

哥 你要不试试这个？
[http://bnci-horizon-2020.eu/database/data-sets](url)
