### ISSUE TITLE
Should the generated data look similar to the original data？

### ISSUE THREAD

**Issue by fanxiao2-zzu-fan** [duanyiqun/DS-DDPM#8]
Hello,
        I would like to ask some questions. I used the ninth EEG signal you provided, but the generated data looks very different from the original data. May I ask, is this consistent with your results? When you have a larger amount of data, does the generated data look consistent with the original data?Thank you!

**Comment by duanyiqun** [comment]
It's a quite good question. 

Actually, I'm also considering this problem. 
The data generated could be very different if we go through the whole sampling process. I suspect that it might contain a large variety of phases for a single wave. But the different shapes do not affect the covariance analysis. This also makes me quite curious. A possible explanation would be the joint effect with all between different phases, different subjects, and even the different waves itself should make the data so different. 

If we use this by assuming the real data as x_1 and only execute the denoising for one step this problem would be alleviated. I use this setting for testing.

**Comment by fanxiao2-zzu-fan** [comment]
> 

Hello, have you ever tried to input only one type of data for training? Is the data generated by the model relatively the same as the original data?

**Comment by fanxiao2-zzu-fan** [comment]
Hello, I input the ninth type of data you provided for training, and the resulting data has a significant difference from the original data. But the generated data looks very similar to the data provided on your GitHub. May I ask if this is a normal phenomenon?

**Comment by duanyiqun** [comment]
No, I haven't tried only using data from one subject, it might not make sense, since if the classifier only sees one piece of data it might not be able to really distinguish unique distributions from each subject.
